modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="changed_creatures"
displayName="Changed: More Creatures-1.20.1"
version="1.3"
credits="§bModel help:\n逸云,洛虹·早春,ChengXi程曦,Zirconia Hui(锆晖)\n§rDev help: 缘来007"
displayURL="https://github.com/hhdsjgit/Changed_Creatures"
logoFile="logo.png"
authors="§4Goodtimes2"
description='''
Some of the content additions to Changed addon plus and Changed :<
And Changed is my favourite mod so I make a lot of things to Changed(-mc) mod
'''

[[dependencies.changed_creatures]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.changed_creatures]]
    modId="changed"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.changed_creatures]]
    modId="changed_addon"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"

